package com.bcooperstl.problem;

public class Problem2 {
	private static final String PROBLEM_DESCRIPTION = 
			"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" + 
			"\n" + 
			"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" + 
			"\n" + 
			"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
	
	public static void main(String[] args) {
		System.out.println(PROBLEM_DESCRIPTION);
		
		Integer total = 2;
		Integer fib1 = 1;
		Integer fib2 = 2;
		Integer fibCurrent = fib1+fib2;
		while (fibCurrent < 4000000) {
			fibCurrent = fib1+fib2;
			if (fibCurrent%2 == 0) {
				total+=fibCurrent;
			}
			fib1 = fib2;
			fib2 = fibCurrent;
		}
		System.out.println("Answer: " + total);
	}

}
